<section style="width: 100%;max-width: 380px;margin: auto;padding: 0.625rem;">
    <h1 class="mb-4 text-center text-crimson">Restablecer contraseña</h1>
    <form class="needs-validation" method="POST">
        <div class="form-group mb-4">
            <small id="emailHelpBlock" class="form-text text-muted mb-4">Introduce tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.</small>
            <?php if(isset($message)): ?>
            <div class="alert alert-success text-center fs-14" role="alert" style="border-radius: .25rem;"><?= htmlspecialchars($success) ?></div>
            <p class="mt-4"><?= htmlspecialchars($message) ?></p>
            <?php else: ?>
            <label for="email">Email</label>
            <input class="form-control <?= empty($email_err) ? '' : 'is-invalid' ?>" type="email" name="email" autocomplete="off" maxlength="50" value="" aria-describedby="emailHelpBlock"/>
            <div class="invalid-feedback"><?= htmlspecialchars($email_err) ?></div>
        </div>
        <button type="submit" class="btn btn-primary btn-lg btn-block mb-4">Enviar email</button>
        <?php endif ?>
    </form>
    <?php if(!isset($message)): ?>
    <p class="text-muted text-center small mb-2">¿Recuerdas tu contraseña? <a href="login.php">Iniciar sesión</a></p>
    <?php endif ?>
</section>