<section style="width: 100%;max-width: 420px;margin: auto;padding: 0.625rem;">
    <h1 class="mb-4">Restablecer contraseña</h1>
    <form class="needs-validation" action="forgot_password.php" method="POST">
        <div class="form-group">
            <label for="email">Email</label>
            <small id="emailHelpBlock" class="form-text text-muted mb-1">Introduce tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.</small>
            <input class="form-control <?= empty($email_err) ? '' : 'is-invalid' ?>" type="email" name="email" autocomplete="off" maxlength="50" value="" aria-describedby="emailHelpBlock"/>
            <div class="invalid-feedback"><?= htmlspecialchars($email_err) ?></div>
        </div>
        <button type="submit" class="btn btn-primary btn-lg px-4 mt-2">Enviar email &raquo;</button>
    </form>
</section>