<section style="width: 100%;max-width: 380px;margin: auto;">
    <h1 class="mb-4">Iniciar sesión</h1>
    <form class="needs-validation" action="login.php" method="POST">
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control <?= empty($email_err) ? '' : 'is-invalid' ?>" type="email" name="email" autocomplete="off" maxlength="50" value="<?= htmlspecialchars( $email ) ?>"/>
            <div class="invalid-feedback"><?= htmlspecialchars($email_err) ?></div>
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <div class="input-group">
                <input class="form-control <?= empty($password_err) ? '' : 'is-invalid' ?>" type="password" name="password" id="password" autocomplete="off" maxlength="50" value="Abc123456/*"/>
                <!-- <div class="input-group-append">
                    <span class="input-group-text showhidden" id="show-password">Mostrar</span>
                </div> -->
                <div class="invalid-feedback"><?= htmlspecialchars($password_err) ?></div>
            </div>
        </div>
        <div class="form-group form-check my-4">
            <a class="float-right fs-14" href="password_reset.php" style="margin-top: .2rem;">¿Olvidó su contraseña?</a>
            <input class="form-check-input" type="checkbox" id="remember_me"/>
            <label class="form-check-label fs-14" for="remember_me">Recordarme</label>
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Ingresar &raquo;</button>
    </form>
</section>