<section style="width: 100%;max-width: 380px;margin: auto;padding: 0.625rem;">
    <h1 class="mb-4 text-center text-crimson">Iniciar sesión</h1>
    <form method="POST" name="login">
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control <?= empty($email_err) ? '' : 'is-invalid' ?>" type="email" name="email" id="email" autocomplete="off" maxlength="50" value="<?= htmlspecialchars( $email ) ?>"/>
            <div class="invalid-feedback"><?= htmlspecialchars($email_err) ?></div>
        </div>
        <!-- <div class="form-group">
            <label for="password">Contraseña</label>
            <div class="input-group">
                <input class="form-control <?= empty($password_err) ? '' : 'is-invalid' ?>" type="password" name="password" id="password" autocomplete="off" maxlength="50" value=""/>
                <div class="invalid-feedback"><?= htmlspecialchars($password_err) ?></div>
                <div class="input-group-append">
                    <span class="input-group-text showhidden">Mostrar</span>
                </div>
            </div>
        </div> -->
        <div class="form-group" style="position: relative;">
            <i class="material-icons visibility">visibility_off</i>
            <label for="password">Contraseña</label>
            <input type="password" class="form-control <?= empty($password_err) ? '' : 'is-invalid' ?>" name="password" id="password" autocomplete="off" maxlength="50" style="padding-right: calc(1.5em + .75rem);">
            <div class="invalid-feedback"><?= htmlspecialchars($password_err) ?></div>
        </div>
        <div class="form-group form-check mb-4">
            <a class="float-right fs-14" href="forgot_password.php" style="margin-top: .2rem;">¿Olvidó su contraseña?</a>
            <input class="form-check-input" type="checkbox" id="remember_me"/>
            <label class="form-check-label fs-14" for="remember_me">Recordarme</label>
        </div>
        <button id="btn" type="submit" class="btn btn-primary btn-block btn-lg mb-4">Ingresar</button>
    </form>
    <p class="text-muted text-center small mb-2">¿Aún no tienes una cuenta? <a href="register.php">Regístrate</a></p>
</section>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        let login = new FormValidator('login', [
        {
            name: 'email',
            display: 'correo electrónico',
            rules: 'required|max_length[50]'
        }, {
            name: 'password',
            display: 'contraseña',
            rules: 'required'
        }], function(errors, evt) {
            if (errors.length > 0) {
                let N = errors.length;
                for (let i = 0; i < N; i++) {
                    errors[i].element.classList.add('is-invalid');
                    errors[i].element.nextElementSibling.innerHTML = errors[i].message;
                }
                errors[0].element.focus();
                evt.preventDefault();
            } else {
                disabledBtn();
            }
        });

        document.addEventListener('DOMContentLoaded', function() {
            checkInput();
        });

        let password = querySelector('#password');
        let visibilityToggle = querySelector('.visibility');


        password.onfocus = checkInput;
        password.oninput = checkInput;
        visibilityToggle.onclick = handleClick;

        function checkInput() {
            if (password.classList.contains('is-invalid')) {
                visibilityToggle.style.top = '38%';
            }else {
                visibilityToggle.style.top = '50%';
            }
            if (password.value.length > 0) {
                visibilityToggle.style.display = "block";
            } else {
                visibilityToggle.style.display = "none";
            }
        }

        function handleClick() {
            let type = password.getAttribute('type');
            let title;
            if (type === 'password') {
                type = 'text';
                visibilityToggle.textContent = 'visibility';
                title = 'Ocultar';
            } else {
                type = 'password';
                visibilityToggle.textContent = 'visibility_off';
                title = 'Mostrar';
            }
            visibilityToggle.setAttribute('title', title + ' contraseña');
            password.setAttribute('type', type);
        }
    });
</script>