<section class="section" style="width: 100%;max-width: 480px;margin: auto;">
    <div class="row">
        <form class="col s12" id="needs-validation" novalidate method="POST">
            <h3 class="">Restablecer contraseña</h3>
            <div class="row">
                <div class="input-field col s12">
                    <label for="email">Email</label>
                    <input id="email" name="email" type="email" class="<?= empty($email_err) ? '' : 'invalid' ?>" value="<?= htmlspecialchars($email) ?>">
                    <span class="helper-text"><?= htmlspecialchars($email_err) ?></span>
                </div>
            </div>
            <button class="btn waves-effect orange" type="submit">
                Enviar correo
            </button>
        </form>
    </div>
</section>