<section class="section" style="width: 100%;max-width: 500px;margin: auto;">
    <div class="row">
        <form class="col s12" id="needs-validation" novalidate method="POST">
            <h3 class="">Restablecer contraseña</h3>
            <div class="row">
                <div class="input-field col s12">
                    <label for="password">Nueva contraseña</label>
                    <input id="password" name="password" type="password" class="<?= empty($password_err) ? '' : 'invalid' ?>">
                    <span class="helper-text"><?= htmlspecialchars($password_err) ?></span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <label for="confirm_password">Confirmar nueva contraseña</label>
                    <input id="confirm_password" name="confirm_password" type="password" class="<?= empty($confirm_password_err) ? '' : 'invalid' ?>">
                    <span class="helper-text"><?= htmlspecialchars($confirm_password_err) ?></span>
                </div>
            </div>
            <input type="hidden" name="id" value="<?= $id ?>" readonly onmousedown="return false;">
            <input type="hidden" name="key" value="<?= $key ?>" readonly onmousedown="return false;">
            <button class="btn waves-effect orange" type="submit">
                Guardar
            </button>
        </form> 
    </div>
</section>