<section class="section" style="width: 100%;max-width: 600px;margin: auto;">
    <div class="row">
        <form class="col s12" id="needs-validation" novalidate method="POST">
            <h3 class="">Registrarse</h3>
            <div class="row">
                <div class="input-field col s6">
                    <label for="first_name">Nombre <span class="required">*</span></label>
                    <input id="first_name" name="nombre" type="text" class="<?= empty($nombre_err) ? '' : 'invalid' ?>" value="<?= htmlspecialchars($nombre) ?>">
                    <span class="helper-text"><?= htmlspecialchars($nombre_err) ?></span>
                </div>
                <div class="input-field col s6">
                    <label for="last_name">Apellido <span class="required">*</span></label>
                    <input id="last_name" name="apellido" type="text" class="<?= empty($apellido_err) ? '' : 'invalid' ?>" value="<?= htmlspecialchars($apellido) ?>">
                    <span class="helper-text"><?= htmlspecialchars($apellido_err) ?></span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <label for="user">Usuario <span class="required">*</span></label>
                    <input id="user" name="usuario" type="text" class="<?= empty($usuario_err) ? '' : 'invalid' ?>" value="<?= htmlspecialchars($usuario) ?>">
                    <span class="helper-text"><?= htmlspecialchars($usuario_err) ?></span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <label for="email">Email <span class="required">*</span></label>
                    <input id="email" name="email" type="email" class="<?= empty($email_err) ? '' : 'invalid' ?>" value="<?= htmlspecialchars($email) ?>">
                    <span class="helper-text"><?= htmlspecialchars($email_err) ?></span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <label for="password">Contraseña <span class="required">*</span></label>
                    <input id="password" name="password" type="password" class="<?= empty($password_err) ? '' : 'invalid' ?>">
                    <span class="helper-text"><?= htmlspecialchars($password_err) ?></span>
                </div>
                <div class="input-field col s6">
                    <label for="confirm_password">Confirmar contraseña <span class="required">*</span></label>
                    <input id="confirm_password" name="confirm_password" type="password" class="<?= empty($confirm_password_err) ? '' : 'is-invalid' ?>">
                    <span class="helper-text"><?= htmlspecialchars($confirm_password_err) ?></span>
                </div>
            </div>
            <button class="btn waves-effect orange" type="submit">
                Registrar
            </button>
        </form>
    </div>
</section>