<section style="width: 100%;max-width: 420px;margin: auto;padding: 15px;">
    <h2 class="mb-4">Restablecer la contraseña</h2>
    <form class="needs-validation" action="password_reset.php" method="POST">
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control <?= empty($email_err) ? '' : 'is-invalid' ?>" type="email" name="email" autocomplete="off" maxlength="50" value=""/>
            <div class="invalid-feedback"><?= htmlspecialchars($email_err) ?></div>
        </div>
        <button type="submit" class="btn btn-success btn-lg px-5">Enviar email <span class="fs-14">&#10095;</span></button>
    </form>
</section>