<section style="width: 100%;max-width: 570px; margin: auto;padding: 0.625rem;">
    <div class="text-center">
        <h1 class="mb-3 text-crimson">Información de la cuenta</h1>
        <p class="mb-4 text-muted fs-14">Cambia tu nombre, apellido, usuario o contraseña.</p>
    </div>
    <form class="needs-validation" action="profile.php" method="POST">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="firstName">Nombre <span class="required">*</span></label>
                <input class="form-control <?= empty($nombre_err) ? '' : 'is-invalid' ?>" type="text" name="nombre" value="<?= htmlspecialchars( $nombre ) ?>" maxlength="32" autocomplete="off" onkeypress="return allow(event, 'car')"/>
                <div class="invalid-feedback"><?= htmlspecialchars($nombre_err) ?></div>
            </div>
            <div class="form-group col-md-6">
                <label for="lastName">Apellido <span class="required">*</span></label>
                <input class="form-control <?= empty($apellido_err) ? '' : 'is-invalid' ?>" type="text" name="apellido" value="<?= htmlspecialchars( $apellido ) ?>" maxlength="32" autocomplete="off" onkeypress="return allow(event, 'car')"/>
                <div class="invalid-feedback"><?= htmlspecialchars($apellido_err) ?></div>
            </div>
        </div>
        <div class="form-group mb-4">
            <label for="usuario">Usuario <span class="required">*</span></label>
            <input class="form-control <?= empty($usuario_err) ? '' : 'is-invalid' ?>" type="text" name="usuario" value="<?= htmlspecialchars( $usuario ) ?>" maxlength="20" autocomplete="off"/>
            <div class="invalid-feedback"><?= htmlspecialchars($usuario_err) ?></div>
        </div>
        <button type="submit" class="btn btn-outline-primary btn-block btn-lg mb-4" name="save_details">Guardar</button>
        <hr class="my-5">
        <div class="form-group">
            <label for="password_actual">Contraseña actual</label>
            <input class="form-control <?= empty($password_actual_err) ? '' : 'is-invalid' ?>" type="password" name="password_actual" maxlength="32" />
            <div class="invalid-feedback"><?= htmlspecialchars($password_actual_err) ?></div>
        </div>
        <div class="form-group">
            <label for="password_1">Nueva contraseña</label>
            <small id="passwordHelpBlock" class="form-text text-muted mb-1 mt-0">Las contraseñas deben tener por lo menos 8 caracteres y tener una combinación de letras, números y otros caracteres.</small>
            <input class="form-control <?= empty($password_1_err) ? '' : 'is-invalid' ?>" type="password" name="password_1" maxLength="32" aria-describedby="passwordHelpBlock"/>
            <div class="invalid-feedback"><?= htmlspecialchars($password_1_err) ?></div>
        </div>
        <div class="form-group mb-4">
            <label for="password_2">Confirmar nueva contraseña</label>
            <input class="form-control <?= empty($password_2_err) ? '' : 'is-invalid' ?>" type="password" name="password_2" maxLength="32"/>
            <div class="invalid-feedback"><?= htmlspecialchars($password_2_err) ?></div>
        </div>
        <input type="hidden" name="id" value="<?= $id ?>" readonly onmousedown="return false;">
        <button type="submit" class="btn btn-outline-primary btn-block btn-lg" name="save_password">Guardar contraseña</button>
    </form>
</section>