<section style="width: 100%;max-width: 520px; margin: auto;padding: 0.625rem;">
    <h1 class="mb-4 text-center text-crimson">Registro de usuario</h1>
    <form class="needs-validation" method="POST">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="firstName">Nombre <span class="required">*</span></label>
                <input class="form-control <?= empty($nombre_err) ? '' : 'is-invalid' ?>" type="text" name="nombre" value="<?= htmlspecialchars( $nombre ) ?>" maxlength="32" autocomplete="off" onkeypress="return allow(event, 'car')"/>
                <div class="invalid-feedback"><?= htmlspecialchars($nombre_err) ?></div>
            </div>
            <div class="form-group col-md-6">
                <label for="lastName">Apellido <span class="required">*</span></label>
                <input class="form-control <?= empty($apellido_err) ? '' : 'is-invalid' ?>" type="text" name="apellido" value="<?= htmlspecialchars( $apellido ) ?>" maxlength="32" autocomplete="off" onkeypress="return allow(event, 'car')"/>
                <div class="invalid-feedback"><?= htmlspecialchars($apellido_err) ?></div>
            </div>
        </div>
        <div class="form-group">
            <label for="usuario">Usuario <span class="required">*</span></label>
            <input class="form-control <?= empty($usuario_err) ? '' : 'is-invalid' ?>" type="text" name="usuario" value="<?= htmlspecialchars( $usuario ) ?>" maxlength="20" autocomplete="off"/>
            <div class="invalid-feedback"><?= htmlspecialchars($usuario_err) ?></div>
        </div>
        <div class="form-group">
            <label for="email">Email <span class="required">*</span></label>
            <input class="form-control <?= empty($email_err) ? '' : 'is-invalid' ?>" type="email" name="email" value="<?= htmlspecialchars( $email ) ?>" maxlength="32" autocomplete="off"/>
            <div class="invalid-feedback"><?= htmlspecialchars($email_err) ?></div>
        </div>
        <div class="form-group">
            <label for="password">Contraseña <span class="required">*</span></label>
            <small id="passwordHelpBlock" class="form-text text-muted mb-1 mt-0">Las contraseñas deben tener por lo menos 8 caracteres y tener una combinación de letras, números y otros caracteres.</small>
            <input class="form-control <?= empty($password_err) ? '' : 'is-invalid' ?>" type="password" name="password" maxlength="32" aria-describedby="passwordHelpBlock"/>
            <div class="invalid-feedback"><?= htmlspecialchars($password_err) ?></div>
        </div>
        <div class="form-group mb-4">
            <label for="confirm_password">Confirmar contraseña <span class="required">*</span></label>
            <input class="form-control <?= empty($confirm_password_err) ? '' : 'is-invalid' ?>" type="password" name="confirm_password" maxLength="32"/>
            <div class="invalid-feedback"><?= htmlspecialchars($confirm_password_err) ?></div>
        </div>
        <button type="submit" class="btn btn-primary btn-block btn-lg mb-4">Registrar</button>
    </form>
    <p class="text-muted text-center small mb-2">¿Ya tienes una cuenta? <a href="login.php">Iniciar sesión</a></p>
</section>