<section style="width: 100%;max-width: 420px;margin: auto;padding: 0.625rem;">
    <h2 class="mb-4">Restablecer contraseña</h2>
    <form class="needs-validation"  method="POST">
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input class="form-control <?= empty($password_err) ? '' : 'is-invalid' ?>" type="password" name="password" id="password" autocomplete="off" maxlength="50" value=""/>
            <div class="invalid-feedback"><?= htmlspecialchars($password_err) ?></div>
        </div>
        <div class="form-group">
            <label for="confirm_password">Confirmar Contraseña</label>
            <input class="form-control <?= empty($confirm_password_err) ? '' : 'is-invalid' ?>" type="password" name="confirm_password" id="confirm_password" autocomplete="off" maxlength="50" value=""/>
            <div class="invalid-feedback"><?= htmlspecialchars($confirm_password_err) ?></div>
        </div>
        <input type="hidden" name="id" value="<?= $id ?>" readonly onmousedown="return false;">
        <input type="hidden" name="key" value="<?= $key ?>" readonly onmousedown="return false;">
        <button type="submit" class="btn btn-primary btn-lg px-4 mt-2">Guardar &raquo;</button>
    </form>
</section>