    	</main>

    	<footer class="small text-center">
            <div class="container">
                <div style="/*border-top: 1px solid #D5DCE5*/;padding: 30px 0;">
                    <p class="">&copy; 2017-<?= htmlspecialchars( date("Y") ) ?> | Powered by JYS | All rights reserved.</p>
                </div>
            </div>
        </footer>

		<a class="cd-top js-cd-top" title="Subir">Top</a>
    	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script type="text/javascript" src="js/main.js"></script>
        <script type="text/javascript" src="js/validation.js"></script>
        <script>
            let dark_switcher = document.querySelector('.dark-switcher');
            let icon = document.querySelector('.theme-icon');
            let list = document.getElementsByTagName("label");
            let n = list.length;

            if (localStorage.getItem("mode") === "dark") {
                showDarkItems();
                icon.src = 'img/light-mode.svg';
            }
            else {
                icon.src = 'img/dark-mode.svg';
                showLightItems();
            }

            dark_switcher.onclick = function handleClick(){
                let src = icon.getAttribute('src');
                if (src == 'img/dark-mode.svg') {
                    localStorage.setItem("mode", "dark");
                    src = 'img/light-mode.svg';
                    showDarkItems();
                } else {
                    localStorage.setItem("mode", "light");
                    src = 'img/dark-mode.svg';
                    showLightItems();
                }
                icon.setAttribute('src', src);
            }

            function showDarkItems() {
                icon.alt = "Light Mode";
                // document.querySelector('.navbar').classList.remove('navbar-light');
                // document.querySelector('.navbar').classList.add('navbar-dark');
                document.body.classList.add('dark');
                document.getElementsByTagName("footer")[0].classList.add("dark");
                document.getElementsByTagName("nav")[0].classList.add("dark");
                for(let i = 0; i < n; i++){
                    list[i].classList.add("dark");
                }
            }
            function showLightItems() {
                icon.alt = "Dark Mode";
                // document.querySelector('.navbar').classList.remove('navbar-dark');
                // document.querySelector('.navbar').classList.add('navbar-light');
                document.body.classList.remove("dark");
                document.getElementsByTagName("footer")[0].classList.remove("dark");
                document.getElementsByTagName("nav")[0].classList.remove("dark");
                for(let i = 0; i < n; i++){
                    list[i].classList.remove("dark");
                }
            }
        </script>
    </body>
</html>