<!DOCTYPE html>
<html lang="en">
    <head>
    	<!-- Required meta tags -->
    	<meta charset="utf-8">
        <meta name="description" content="My first web page">
        <meta name="keywords" content="HTML,CSS,PHP,JavaScript">
        <meta name="author" content="JYS">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    	<!-- Bootstrap CSS -->
    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	    <?php if(isset($title)): ?>
        <title>PhpApp - <?= htmlspecialchars($title) ?></title>
        <?php else: ?>
        <title>PhpApp</title>
        <?php endif ?>
	    <link rel="stylesheet" type="text/css" href="css/material.css">
        <link rel="stylesheet" type="text/css" href="css/styles.css">
    </head>
    <body>
    	<nav class="navbar navbar-expand-md navbar-light border-bottom shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="#" style="font-size: 16px; font-weight: 500">PhpApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a></li>
                    </ul>
                    <?php if (!isset($_SESSION['user_id'])): ?>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link" href="login.php">Ingresar</a></li>
                        <li class="nav-item"><a class="nav-link" href="register.php">Registrarse</a></li>
                    </ul>
                    <?php else: ?>
                    <ul class="navbar-nav ml-auto">
                        <span class="navbar-text mr-md-2">Bienvenido &nbsp;<span class=""><?= htmlspecialchars($_SESSION['user_name']) ?>!</span></span>
                        <li class="nav-item"><a class="nav-link" href="logout.php">Salir</a></li>
                    </ul>
                    <?php endif ?>
                </div>
            </div>
        </nav>
    	<header>
            <?php
            flash('flash_success');
            flash('flash_error');
            ?>
    	</header>

    	<main role="main" class="container my-5">