        </main>

        <footer style="margin-bottom: 30px; margin-top: 30px; font-size: .9rem;">
            <div class="container center">
                <p class="grey-text text-darken-1">&copy; 2017-<?= htmlspecialchars( date("Y") ) ?> | Powered by JYS | All rights reserved.</p>
            </div>
        </footer>
        <a class="cd-top js-cd-top" title="Subir">Top</a>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('.sidenav');
                var instances = M.Sidenav.init(elems);
            });
        </script>
        <script type="text/javascript" src="js/main.js"></script>
        <script type="text/javascript" src="js/validation.js"></script>
    </body>
</html>