<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="My first web page">
        <meta name="keywords" content="HTML,CSS,PHP,JavaScript">
        <meta name="author" content="JYS">
        <link rel="icon" href="img/favicon.ico" type="image/x-icon">
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <link rel="stylesheet" type="text/css" href="css/styles.css">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <?php if(isset($title)): ?>
        <title>PhpApp - <?= htmlspecialchars($title) ?></title>
        <?php else: ?>
        <title>PhpApp</title>
        <?php endif ?>
        <style type="text/css">
            .row{margin-bottom: unset;}
            .required, .helper-text{color: red!important;}
        </style>
    </head>

    <body>
        <?php
            require_once 'm-navbar.phtml';
            flash('success');
            flash('error');
        ?>
        <main class="container section">