<nav class="navbar navbar-expand-md navbar-dark shadow-sm" style="background-color: #344D90;">
    <div class="container">
        <a class="navbar-brand mb-1" href="index.php">Julio Cesar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="about.php">Acerca</a></li>
                <li class="nav-item"><a class="nav-link" href="quiz.php">Ponte a prueba</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <span class="navbar-text mr-sm-2 dark-switcher" title="Alternar modo oscuro" style="cursor: pointer;"><img class="theme-icon mb-1" src="img/dark-mode.svg"></span>
                
            <?php if (isset( $_SESSION['user_id'] )):
                $user = getUser($_SESSION['user_id']);
            ?>
                <li class="nav-item"><a class="nav-link" href="index.php">Posts</a></li>
                <li class="nav-item"><a class="nav-link" href="profile.php">Perfil</a></li>
                <span class="navbar-text mr-sm-3 ml-sm-2">Bienvenido &nbsp;<span style=""><?= htmlspecialchars($user['user_name']) ?>!</span></span>
                <!-- <li class="nav-item"><a class="nav-link" href="logout.php">Salir</a></li> -->
            </ul>
            <form class="form-inline my-2 my-lg-0" action="logout.php" method="POST">
                <button type="submit" class="btn btn-primary my-2 my-sm-0 px-2 py-1" onclick="return confirm('¿Deseas cerrar la sesión?');">Salir</button>
            </form>
            <?php else: ?>
                <li class="nav-item"><a class="nav-link" href="register.php">Registrarse</a></li>
                <li class="nav-item"><a class="nav-link" href="login.php">Ingresar</a></li>
            </ul>
            <?php endif ?>
        </div>
    </div>
</nav>