<nav class="navbar navbar-expand-md navbar-dark bg-dark border-bottom shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="index.php">PostsApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="index.php">Inicio <span class="sr-only">(current)</span></a></li>
                <li class="nav-item"><a class="nav-link" href="about.php">Acerca</a></li>
            </ul>
            <?php if (isset( $_SESSION['user_id'] )):
                $user = getUser($_SESSION['user_id']);
            ?>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="index.php">Posts</a></li>
                <li class="nav-item"><a class="nav-link" href="profile.php">Perfil</a></li>
                <span class="navbar-text mx-md-2">Bienvenido &nbsp;<span style=""><?= htmlspecialchars($user['user_name']) ?>!</span></span>
                <!-- <li class="nav-item"><a class="nav-link" href="logout.php">Salir</a></li> -->
            </ul>
            <form class="form-inline my-2 my-lg-0" action="logout.php" method="POST">
                <button type="submit" class="btn btn-outline-primary my-2 my-sm-0 px-2 py-1">Salir</button>
            </form>
            <?php else: ?>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="register.php">Registrarse</a></li>
                <li class="nav-item"><a class="nav-link" href="login.php">Ingresar</a></li>
            </ul>
            <?php endif ?>
        </div>
    </div>
</nav>