<section>
    <h2 class="mb-4">Usuarios Registrados</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Apellido</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Usuario</th>
                    <th>Creado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user): ?>
                    <tr>
                        <td><?= $user['user_id'] ?></td>
                        <td><?= $user['last_name'] ?></td>
                        <td><?= $user['first_name'] ?></td>
                        <td><?= $user['user_email'] ?></td>
                        <td><?= $user['user_name'] ?></td>
                        <td><?= $user['created_on'] ?></td>
                        <td>
                            <a href="" class="" title="Edit">Edit</a>&nbsp;
                            <a href="" class="" onclick="return confirm('¿Estás absolutamente seguro que quieres eliminar a ' + '<?= htmlspecialchars($user['last_name'] . ' ' . $user['first_name']) ?>?')" title="Delete">Delete</a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</section>