<div class="section" style="padding: 0.625rem;">
	<h1 class="text-crimson mb-4" style="font-size: 2.125rem;">PostsApp</h1>
	<p>PostsApp es una aplicación desarrollada con PHP, que tiene como objetivo la publicación de pensamientos, ideas y percepciones sobre la situación del mundo actual en el que vivimos. De modo que podamos reflexionar sobre la compleja realidad en la que nos encontramos inmersos.</p>
	<p>version: <strong><i class="material-icons mr-1">build </i><?= htmlspecialchars(APP_VERSION); ?></strong></p>
</div>